version: '3'

services:

  yapi:
    build: .
    ports:
      - 3000:3000
    network_mode: host
    restart: always
    volumes:
      - ./config.json:/vendors/config.json
    privileged: true

volumes:
  mongo_data_yapi:

